podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven', image: 'maven:3.6.1-jdk-11-slim', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.16.0', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {

        stage('Clone repository') {
            container('git') {
                checkout scm
            }
        }

        stage('Build') {
            container('maven') {
                dir("${env.JOB_NAME}/server") {
                    configFileProvider([configFile(fileId: 'maven-settings', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
                        sh 'mvn -gs $MAVEN_GLOBAL_SETTINGS -DskipTests clean package'
                    }
                }
            }
        }

        stage('Test') {
            container('maven') {
                dir("${env.JOB_NAME}/server") {
                    configFileProvider([configFile(fileId: 'maven-settings', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
                        sh 'mvn -gs $MAVEN_GLOBAL_SETTINGS test'
                    }
                }
            }
        }

        stage('Build docker image') {
            container('docker') {
                dir("${env.JOB_NAME}/server") {
                    sh "docker build -t ${env.JOB_NAME}:${env.BUILD_ID} -t ${env.JOB_NAME}:latest ."
                }
            }
        }

        stage('Deploy') {
            container('kubectl') {
                dir("${env.JOB_NAME}/server") {
                    sh "kubectl proxy &"
                    sh "sed -i 's/\$BUILD_ID/${env.BUILD_ID}/g' manifest.yaml"
                    sh "kubectl apply -f manifest.yaml --namespace=default"
                }
            }
        }
    }
}