apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        app: fima
        tier: frontend
        track: stable
        name: api
    spec:
      containers:
        - name: api
          image: "$DOCKER_IMAGE"
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: fima
    tier: frontend
    name: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-route

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.fima.test`)
      kind: Rule
      services:
        - name: api
          port: 80