pipeline {
    agent any

    tools {
        maven 'Maven 3.3.9'
    }

    stages {
        stage('Clone repository') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('transaction-import-service/server') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('transaction-import-service/server') {
                    sh 'mvn test'
                }
            }
        }

        stage('Push docker image') {
            steps {
                script {
                    echo env.DOCKER_REGISTRY

                    docker.withRegistry("http://$env.DOCKER_REGISTRY") {
                        def customImage = docker.build("${env.JOB_NAME}:${env.BUILD_ID}", "--insecure-registry ${env.DOCKER_REGISTRY} ./transaction-import-service/server")

                        customImage.push()
                    }
                }
            }
        }
    }
}