pipeline {
    agent any

    tools {
        maven 'Maven 3.3.9'
    }

    stages {
        stage('Clone repository') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('transaction-import-service/server') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('transaction-import-service/server') {
                    sh 'mvn test'
                }
            }
        }

        stage('Push docker image') {
            steps {
                script {
                    docker.withRegistry(env.DOCKER_REGISTRY, 'nexus-docker-registry') {
                        docker.build("${env.JOB_NAME}:${env.BUILD_ID}", './transaction-import-service/server').push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "cat transaction-import-service/server/manifest.yaml | sed 's/\$BUILD_ID/${env.BUILD_ID}/g'"
                    sh "cat transaction-import-service/server/manifest.yaml | sed 's/\$BUILD_ID/${env.BUILD_ID}/g' | kubectl apply -f -"
                }
            }
        }
    }
}