podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.16.0', command: 'cat', ttyEnabled: true)
  ],
  volumes: []
  ) {
    node('mypod') {
        stage('Clone repository') {
            container('git') {
                checkout scm
            }
        }

        stage('Deploy') {
            container('kubectl') {
                dir("${env.JOB_NAME}") {
                    sh "kubectl apply -f manifest.yaml --namespace=default"
                }
            }
        }
    }
}