apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: investment-service
  template:
    metadata:
      labels:
        app: fima
        tier: backend
        track: stable
        name: investment-service
    spec:
      containers:
        - name: investment-service
          image: "$DOCKER_IMAGE"
          ports:
            - name: http
              containerPort: 9997
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fima-postgres-db-pass
                  key: password
            - name: ALPHA_VANTAGE_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: fima-alpha-vantage-api
                  key: base_url
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fima-alpha-vantage-api
                  key: api_key
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: investment-service
spec:
  selector:
    app: fima
    tier: backend
    name: investment-service
  ports:
    - name: http
      protocol: TCP
      port: 9997
      targetPort: http
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: api.fima.test
      http:
        paths:
          - path: /investment
            backend:
              serviceName: api
              servicePort: 8080