apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: transaction-service
  template:
    metadata:
      labels:
        app: fima
        tier: backend
        track: stable
        name: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: "$DOCKER_REGISTRY_PREFIX/transaction-service@$IMAGE_HASH"
          ports:
            - name: http
              containerPort: 9997
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fima-mysql-db-pass
                  key: password
            - name: KAFKA_HOST
              value: 10.108.62.237
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: transaction-service
spec:
  selector:
    app: fima
    tier: backend
    name: transaction-service
  ports:
    - name: http
      protocol: TCP
      port: 9997
      targetPort: http