pipeline {
    agent any

    tools {
        maven 'Maven 3.3.9'
    }

    stages {
        stage('Clone repository') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir("${env.JOB_NAME}/server") {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${env.JOB_NAME}/server") {
                    sh 'mvn test'
                }
            }
        }

        stage('Push docker image') {
            steps {
                script {
                    docker.withRegistry(env.DOCKER_REGISTRY, 'nexus-docker-registry') {
                        docker.build("${env.JOB_NAME}:${env.BUILD_ID}", "./${env.JOB_NAME}/server").push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    dir("${env.JOB_NAME}/server") {
                        sh "sed -i 's/\$BUILD_ID/${env.BUILD_ID}/g' manifest.yaml"
                        sh "sed -i 's/\$NEXUS_HOST/${env.NEXUS_HOST}/g' manifest.yaml"
                        sh "kubectl apply -f manifest.yaml --v=9"
                    }
                }
            }
        }
    }
}