podTemplate(
    label: 'build-slave',
    containers: [
        containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.23.6', command: 'cat', ttyEnabled: true)
    ],
    volumes: []
) {
    node('build-slave') {
        stage('Clone repository') {
            container('git') {
                checkout scm
            }
        }

        stage('Deploy') {
            container('kubectl') {
                dir("infrastructure/${env.JOB_NAME}") {
                    sh "kubectl apply -f '*.yaml' --namespace=default"
                }
            }
        }
    }
}