podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {
        stage('Check running containers') {
            container('docker') {
                sh 'docker ps'
            }
        }

        stage('Clone repository') {
            container('git') {
                cleanWs()
                checkout scm
            }
        }

        stage('Build') {
            container('maven') {
                dir("${env.JOB_NAME}") {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }

        stage('Test') {
            container('maven') {
                dir("${env.JOB_NAME}") {
                    sh 'mvn test'
                }
            }
        }
    }
}