apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: transaction-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fima
        tier: frontend
        track: stable
        name: transaction-api
    spec:
      containers:
        - name: transaction-api
          image: "transaction-api:latest"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: transaction-api
spec:
  selector:
    app: fima
    tier: frontend
    name: transaction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transaction-api
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: api.fima.dev
    http:
      paths:
      - path: /transaction
        backend:
          serviceName: transaction-api
          servicePort: 80