pipeline {
    agent any

    tools {
        nodejs 'NodeJS 8.11.2'
    }

    stages {
        stage('Clone repository') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir("${env.JOB_NAME}") {
                    sh 'npm run build'
                }
            }
        }

        stage('Push docker image') {
            steps {
                script {
                    docker.withRegistry(env.DOCKER_REGISTRY, 'nexus-docker-registry') {
                        docker.build("${env.JOB_NAME}:${env.BUILD_ID}", "./${env.JOB_NAME}").push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    dir("${env.JOB_NAME}") {
                        sh "sed -i 's/\$BUILD_ID/${env.BUILD_ID}/g' manifest.yaml"
                        sh "sed -i 's/\$NEXUS_HOST/${env.NEXUS_HOST}/g' manifest.yaml"
                        sh "kubectl apply -f manifest.yaml"
                    }
                }
            }
        }
    }
}