podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'node', image: 'node:8.16.0-alpine', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.15.1', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]
  ) {
    node('mypod') {

        stage('Clone repository') {
            container('git') {
                checkout scm
            }
        }

        stage('Build') {
            container('node') {
                dir("${env.JOB_NAME}") {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Build docker image') {
            container('docker') {
                dir("${env.JOB_NAME}") {
                    sh "docker build -t ${env.DOCKER_REGISTRY_PREFIX}/${env.JOB_NAME}:${env.BUILD_ID} -t ${env.DOCKER_REGISTRY_PREFIX}/${env.JOB_NAME}:latest ."
                    sh "docker push ${env.DOCKER_REGISTRY_PREFIX}/${env.JOB_NAME}:${env.BUILD_ID}"
                }
            }
        }

        stage('Deploy') {
            container('kubectl') {
                dir("${env.JOB_NAME}") {
                    sh "sed -i 's/\$DOCKER_REGISTRY_PREFIX/${env.DOCKER_REGISTRY_PREFIX}/g' manifest.yaml"
                    sh "sed -i 's/\$BUILD_ID/${env.BUILD_ID}/g' manifest.yaml"
                    sh "kubectl apply -f manifest.yaml --namespace=default"
                }
            }
        }
    }
}
