apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-frontend
  template:
    metadata:
      labels:
        app: fima
        tier: frontend
        track: stable
        name: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: "$DOCKER_REGISTRY_PREFIX/web-frontend:$BUILD_ID"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: fima-api
                  key: host
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: web-frontend
spec:
  selector:
    app: fima
    tier: frontend
    name: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-frontend-route
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fima.test`)
      kind: Rule
      services:
        - name: web-frontend
          port: 80