podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven', image: 'maven:3.6.1-jdk-11-slim', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
      secretVolume(mountPath: '/home/jenkins/.ssh', secretName: 'ssh-key')
  ]
) {
    node('mypod') {

        stage('Clone repository') {
            container('git') {
                dir("${env.JOB_NAME}") {
                    sh """
                        mkdir /root/.ssh
                        cp -L /home/jenkins/.ssh/* /root/.ssh
                        chmod -R 400 /root/.ssh
                        GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:lbunschoten/fima.git
                    """
                }
            }
        }

        stage('Build') {
            container('maven') {
                dir("${env.JOB_NAME}") {
                    configFileProvider([configFile(fileId: 'maven-settings', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
                        sh "mvn --no-transfer-progress -gs $MAVEN_GLOBAL_SETTINGS -f fima/transaction-domain/pom.xml versions:set -DnewVersion=${RELEASE_VERSION}"
                        sh "mvn --no-transfer-progress -gs $MAVEN_GLOBAL_SETTINGS -f fima/transaction-domain/pom.xml clean deploy"
                    }
                }
            }
        }
    }
}