apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  labels:
    app: fima
    name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fima
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: fima/jenkins:0.9.6
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false -Xmx1024m
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home
          resources:
            limits:
              memory: 1.2Gi
            requests:
              memory: 1.0Gi
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins-volume-claim
      hostAliases:
        - ip: "192.168.64.3"
          hostnames:
            - "jenkins.fima.dev"
            - "nexus.fima.dev"
            - "docker-registry.fima.dev"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http-port
      name: http
    - port: 50000
      targetPort: jnlp-port
      name: jnlp
  selector:
    app: fima
    name: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: jenkins.fima.dev
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 8080