apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-import-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: transaction-import-service
  template:
    metadata:
      labels:
        app: fima
        tier: backend
        track: stable
        name: transaction-import-service
    spec:
      containers:
        - name: transaction-import-service
          image: "$DOCKER_REGISTRY_PREFIX/transaction-import-service@$IMAGE_HASH"
          ports:
            - name: http
              containerPort: 9997
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: transaction-import-service
spec:
  selector:
    app: fima
    tier: backend
    name: transaction-import-service
  ports:
    - protocol: TCP
      port: 9997
      targetPort: http