kind: Service
apiVersion: v1
metadata:
  name: fima-transaction-api
spec:
  selector:
    app: fima
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 8891
      targetPort: 8891
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fima-transaction-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fima
        tier: frontend
        track: stable
    spec:
      containers:
        - name: fima-transaction-api
          image: "fima-transaction-api:1.0"